-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1035
--   at:        2018-05-08 01:04:32 EEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE brand (
    brand_id     NUMERIC(3) NOT NULL identity(1,1),
    brand_name   VARCHAR(20) NOT NULL
)

ALTER TABLE Brand ADD constraint brand_pk PRIMARY KEY CLUSTERED (Brand_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
    
    GO
    ALTER TABLE brand add constraint brandname_uk unique nonclustered(brand_name)


CREATE TABLE category (
    category_id     NUMERIC(3) NOT NULL  identity(1,1),
    category_name   VARCHAR(10) NOT NULL
)
   

ALTER TABLE Category ADD constraint category_pk PRIMARY KEY CLUSTERED (Category_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
    
  
    ALTER TABLE category add constraint categoryname_uk unique nonclustered(category_name)
     

CREATE TABLE color (
    color_id     VARCHAR(7) NOT NULL ,
    color_name   VARCHAR(10) NOT NULL
)
    

ALTER TABLE Color ADD constraint color_pk PRIMARY KEY CLUSTERED (Color_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     
    
    ALTER TABLE color add constraint colorname_uk unique nonclustered(color_name)
     

CREATE TABLE images (
    image_url    VARCHAR(100) NOT NULL,
    product_id   NUMERIC(6) NOT NULL 
)
    

CREATE TABLE products (
    product_id     NUMERIC(6) NOT NULL  identity(1,1),
    name           VARCHAR(20) NOT NULL,
    price          DECIMAL(7,2) NOT NULL,
    size           VARCHAR(4),
    discount       NUMERIC(2),
    for_what_age   NUMERIC(2),
    second_hand    bit DEFAULT 1,
    user_id        NUMERIC(6) NOT NULL,
    category_id    NUMERIC(3) NOT NULL,
    color_id       VARCHAR(7) NOT NULL,
    brand_id       NUMERIC(3) NOT NULL,
    isavailable    bit
)
  

ALTER TABLE Products ADD constraint products_pk PRIMARY KEY CLUSTERED (Product_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     
CREATE TABLE shopping_cart (
    user_id      NUMERIC(6) NOT NULL,
    product_id   NUMERIC(6) NOT NULL
)


CREATE TABLE user_details (
    user_id         NUMERIC(6) NOT NULL,
    gender          CHAR(1),
    country         VARCHAR(20),
    city            VARCHAR(20),
    shoes_size      NUMERIC(3,1),
    clothes_size    VARCHAR(4),
    balance         DECIMAL(7,2),
    phone_number    NUMERIC(15),
    date_of_birth   DATE
)
    

    


CREATE UNIQUE NONCLUSTERED INDEX 
    User_Details__IDX ON user_details ( user_id ) 


CREATE TABLE users (
    user_id         NUMERIC(6) NOT NULL  identity(1,1),
    email_address   VARCHAR(20) NOT NULL,
    password        VARCHAR(20) NOT NULL,
    fisrt_name      VARCHAR(20) NOT NULL,
    last_name       VARCHAR(20) NOT NULL,
    administrator   bit DEFAULT 0
)
   

ALTER TABLE Users 
    ADD CONSTRAINT constrain_CK 
    CHECK ( len(password) >= 6 )

ALTER TABLE Users ADD constraint users_pk PRIMARY KEY CLUSTERED (User_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
   
    ALTER TABLE users add constraint emailaddress_uk unique nonclustered(email_address)
   

ALTER TABLE Products
    ADD CONSTRAINT brandproductrelation FOREIGN KEY ( brand_id )
        REFERENCES brand ( brand_id )
ON DELETE NO ACTION 
    

ALTER TABLE Products
    ADD CONSTRAINT categoryproductrelation FOREIGN KEY ( category_id )
        REFERENCES category ( category_id )
ON DELETE NO ACTION 
   

ALTER TABLE Products
    ADD CONSTRAINT colorproductrelation FOREIGN KEY ( color_id )
        REFERENCES color ( color_id )
ON DELETE NO ACTION 
  

ALTER TABLE Images
    ADD CONSTRAINT productimagesrelation FOREIGN KEY ( product_id )
        REFERENCES products ( product_id )
ON DELETE NO ACTION 

ALTER TABLE Shopping_cart
    ADD CONSTRAINT productshoppingcartrelation FOREIGN KEY ( product_id )
        REFERENCES products ( product_id )
ON DELETE NO ACTION 

ALTER TABLE Products
    ADD CONSTRAINT userproductrelation FOREIGN KEY ( user_id )
        REFERENCES users ( user_id )
ON DELETE NO ACTION 

ALTER TABLE User_Details
    ADD CONSTRAINT userrelation FOREIGN KEY ( user_id )
        REFERENCES users ( user_id )
ON DELETE NO ACTION 

ALTER TABLE Shopping_cart
    ADD CONSTRAINT usershoppingcart FOREIGN KEY ( user_id )
        REFERENCES users ( user_id )
ON DELETE NO ACTION 




-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
